# Change these first
owner: wesreckless # Your GitHub organization or username, where this repository lives
repo: upptime_test # The name of this repository

sites:
  - name: www.sentraland.net
    url: https://www.sentraland.net
  - name: PST3 Sentraland
    url: https://sent.sentraland.net
  - name: PST2 Sentraland
    url: https://www.amspst.cl:8443/PSTadmin/init.do
  - name: PST NetUno
    url: https://sms.netuno.cl:8443/PSTNetUno/init.do
  - name: PST Movistar
    url: https://pst.movistar.cl:8443/PSTadmin/init.do
  - name: La Araucana Convenios
    url: https://convenios.laaraucana.cl/
  - name: Club Metrogas
    url: https://www.clubmetrogas.cl/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptime_test
  name: SENTRALAND
  favicon: https://i.ibb.co/C7ZT6YD/favicon.png
  logoUrl: https://i.ibb.co/K5P1ccS/logo.png
  navbar:
    - title: Todos
      href: https://wesreckless.github.io/upptime_test
    - title: Sentraland
      href: https://wesreckless.github.io/upptime_test/history/sentraland

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
